### ISSUE TITLE
autoscaler is not triggered

### ISSUE THREAD

**Issue by shaoyongfeng** [gardener/autoscaler#104]
**What happened**:
Node is not scaled up automatically
**What you expected to happen**:
Node in my cluster should be scaled up automatically  if pod can't be scheduled due to resource limitation.
**How to reproduce it (as minimally and precisely as possible)**:
1. create a shoot in dashboard
2. set autoscaler min as 1 in worker group
3. choose 2 zones in worker group
4. once shoot is ready, try to create workload to trigger autoscale
Actual result:
I saw error in cluster autoscaler pod:
E1213 07:14:02.234578 1 static_autoscaler.go:428] Failed to scale up: Could not compute total resources: No node info for: shoot--iotalidev--dev40-a-worker-m1ih4-eu-west-1b

**Anything else we need to know**:
One example shoot from user is https://dashboard.garden.canary.k8s.ondemand.com/namespace/garden-iotalidev/shoots/dev40-a/
**Environment**:

**Comment by vlerenc** [comment]
/duplicate https://github.com/gardener/machine-controller-manager/issues/798 is the actual root of the problem. The auto-scaler does it's job, but how it's set up is the culprit, I think.
/close

**Comment by shaoyongfeng** [comment]
HI @vlerenc ,
But for my case, I think auto scaler should handle it correctly even if user config worker pool as I described

**Comment by vlerenc** [comment]
@shaoyongfeng Well, it starts with Gardener because it should make this more intuitive. What happens after what you did is a pool with no machine/node, so CA complains as the way how CA is implemented by the community is to not have but extract the properties from node resources, but since you have none as the worker pool has 0 nodes, it cannot do that.

That is what we call scale-to/from-zero. The community CA simply cannot do that. We plan to add it for our provider with https://github.com/gardener/autoscaler/issues/103.

So, the confusing part is https://github.com/gardener/machine-controller-manager/issues/798. The generic scale-to/from-zero part is gardener/gardener#103.
