### ISSUE TITLE
[Feature] Support zero sized worker-pools 

### ISSUE THREAD

**Issue by PadmaB** [gardener/autoscaler#20]
**Feature (What you would like to be added):**
As a consumer, I should be able to define worker-pools with min value as zero

**Motivation (Why is this needed?):**
In certain usecases, it will be necessary to define worker-pools of different machines but control the active instances [especially the larger instances] based on the load. Currently it is not possible to define a worker pool with min as zero, this means there will atleast be one active instance in the worker-pool idling and is not cost effective [especially for larger resources] 

**Approach/Hint to the implement solution (optional):**
TBD

**Comment by rfranzke** [comment]
Do we really need to support this in the autoscaler? Instead, we could also modify Gardener to allow this and simply omit those machine deployments in the the autoscaler's configuration?

**Comment by PadmaB** [comment]
Isn't this approach over-riding the autoscaler behavior itself? 
AFAIK, autoscaler will not be able to identify which worker-pool to scale when required in case the min is zero. Hence, the size should be atleast one
@hardikdr your inputs?

**Comment by rfranzke** [comment]
Yes, sure, we could fix it in the autoscaler anyways. Just saying that if we want to have the feature that people can use worker pools with min=0 then you could also implement this (maybe much quicker?) in Gardener itself.

**Comment by prashanth26** [comment]
There are two parts to the problem here,

1. Support workers where `min=0` is possible. --->  This can be handled by omitting the `machine deployment` as mentioned above. This is something that is _manually triggered_ by cluster owners.

2. Support CA to scale workers from 0-Max --->  This makes sense in scenarios where machines with special properties (e.g. GPU) might not always be required. So in such cases, the CA can automatically scale the machine deployment it to 0 and scale up again on requirements. This is something that the _CA has to handle automatically_.

**Comment by rewiko** [comment]
Hello, 

We've implemented [this feature](https://github.com/gardener/autoscaler/issues/20#issuecomment-518154237) on the machine-controller-manager and the autoscaler.
We have something working, just need to clean the code.
PR will be created soon.

**Comment by rewiko** [comment]
Hi, 

I have created the 2 PRs, ideally we should add more tests, but that will allow everyone to see the change and having feedback.
[Allow mcm provider to scale down to 0](https://github.com/gardener/autoscaler/pull/26)  
[Update status when replicas undefined or equal to zero](https://github.com/gardener/machine-controller-manager/pull/387)

**Comment by prashanth26** [comment]
Reopening issue in favor of pending changes on autoscaler - https://github.com/gardener/autoscaler/pull/26

**Comment by DanielZhangQD** [comment]
Hi,  if I configure a worker group with min=1, max=3 in one region of 3 zones, only one node group (--nodes=1:1:shoot--core--x.shoot--core--x-tidb-z1) will be configured for cluster auto-scaler, then when we need more nodes later, only nodes in this node group(dedicated in one zone) will be scaled, is this issue gonna fixed by #26 & #27?

**Comment by rewiko** [comment]
@DanielZhangQD if you only define one node groups on the autoscaler config then it will only scale that one.

I'm not sure I understand your issue. 
I would recommend to have at least one nodegroups/machinedeployments per AZ, then you sould define the 3 machine deployments to the cluster-autoscaler parameter, and you can add `--scale-similar-node-groups=true` to make sure your nodes are spread evenly accross the 3 AZ.

That will work nicely as long your minimun is greater than 0. That will also work with minimum set to 0 for AWS and Azure, we are planning to add more provider as part of this issue. All providers should work if the minimum is greater than 0.

**Comment by DanielZhangQD** [comment]
@rewiko Thanks for your reply!

**Comment by hardikdr** [comment]
We already have support for AWS and Azure, the generic support is yet to be worked upon. 
/close in favor of https://github.com/gardener/autoscaler/issues/27
