### ISSUE TITLE
Avoid fixing nodegroup size

### ISSUE THREAD

**Issue by hardikdr** [gardener/autoscaler#30]
## Issue
Cluster autoscaler currently seems to be trying to fix the node-group size if there is any inconsistency between the number of registered nodes and Machine-objects. CA may do this by reducing the targetSize of node-group, which is disruptive. We should investigate to disable such a feature.

Ref:
- https://github.com/kubernetes/autoscaler/blob/dbbd4572af2b666d32e582bf88c4239163706f8c/cluster-autoscaler/core/static_autoscaler.go#L332-L335
- https://github.com/kubernetes/autoscaler/blob/dbbd4572af2b666d32e582bf88c4239163706f8c/cluster-autoscaler/core/static_autoscaler.go#L542:6 

Update:  It can possibly also scale-down below `min`, which is even more disruptive.

**Comment by vlerenc** [comment]
Thanks for following up.

**Comment by himanshu-kun** [comment]
An issue has been seen currently where this mechanism scales below `min`. 
Although it didn't disrupt anything as it removed long unregistered nodes, the only thing is autoscaler won't try to scale that node grp up to minimum until we have an unschedulable pod requesting that scale-up.
So dashboard would have errors like `Not enough worker nodes`.
This could be solved by reconciling the shoot because then the worker controller will trigger a scale-up to maintain the minimum.

**Comment by himanshu-kun** [comment]
## Post grooming decision

Currently we have commented out the `fixNodeGroupSize` logic in the PR #160 
But we'll need to relook at how clusterAPI is doing it , as commenting core code makes our fork more diverged to the upstream code.

We'll also need to update the FAQ , maybe a section `How gardener autoscaler diverges from k8s autoscaler` , where we add this change.
