### ISSUE TITLE
Plans to upstream mcm provider or sync w/ upstream release cycle?

### ISSUE THREAD

**Issue by jsravn** [gardener/autoscaler#89]
**What would you like to be added**:

Upstream CA only promises compatibility with the matching kubernetes version. E.g. cluster-autoscaler 1.20 is expected to be run with Kubernetes 1.20. This is mostly so the scheduling decisions match between the k8s scheduler and CA.

This fork doesn't make the distinction, so it's not clear what version of k8s it is compatible with.

I wonder if there are any plans to remedy this. I was thinking either by upstreaming the mcm provider into CA, or by following the same branch process of upstream.

**Why is this needed**:

So we don't run into issues using incompatible CA versions.

**Comment by prashanth26** [comment]
Hi @jsravn .

I think you have a fair point. We will try to tabulate the compatibility support as in the upstream CA releases. We plan to update the CA very soon and once we do this we will try to tabulate these supports. 

>I wonder if there are any plans to remedy this. I was thinking either by upstreaming the mcm provider into CA, or by following the same branch process of upstream.

We have discused this internally in the past, however haven't got to it due to some feature compatibility issues like scale to/from zero suppport etc. But yes, ideally we would like to use the upstream branch as well. Refer - https://github.com/gardener/autoscaler/issues/32.

**Comment by himanshu-kun** [comment]
/close
We now maintain a release matrix to address the issue -> https://github.com/gardener/autoscaler/tree/machine-controller-manager-provider/cluster-autoscaler#releases-gardenerautoscaler
