### ISSUE TITLE
pod didn't trigger scale-up when node is vSMP MemoryOne based and cluster was started with zero nodes in the group

### ISSUE THREAD

**Issue by talnevo** [gardener/autoscaler#95]
**vSMP MemoryOne** provides the ability to have a node with more memory than the AWS instance it uses provides.
This is done by using virtualization to make fast NVMe drives appear as part of RAM.

**EXAMPLE**: an m5d.2xlarge instance that has 32GB of RAM can boot with **vSMP MemoryOne** as a 128GB node.

In such a case, provisioning a pod that require 90GB should trigger a scale-up for such a node.

However: 
1. if the cluster starts with zero such nodes (min=0), the auto-scaler fails to provision one for the pod.
2. If the cluster is started with one such node (min=1), the auto-scaler is able to provision new nodes for such pods.
3. If provisioning for a large pod fails (min=0) and then provisioning is requested for another pod that is smaller than 32GB, that second provisioning succeeds, a node is provisioned, and after that any previously failed provisioning actually succeeds.

It looks as though the auto-scaler will use the actual memory size of a node when one is already up, but will use the size of the AWS instance otherwise.

Is it possible to override this behavior and make the auto-scaler aware of the eventual size of the node before any such node is present?

The event that shows up when provisioning fails is:
> **Normal   NotTriggerScaleUp  7m30s                  cluster-autoscaler  pod didn't trigger scale-up (it wouldn't fit if a new node is added)**

**Comment by hardikdr** [comment]
Had a brief chat with @talnevo and Nir.

Reg 1, 2)
The issue is related to the behavior where the memory-capacity of the machine is modified at the runtime, which confuses the scale from the zero feature. Possible solution could be to have a dedicated vSMP related machine types here - https://github.com/gardener/autoscaler/blob/machine-controller-manager-provider/cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go . 
- These may require necessary adaptations in MCM and Gardener's cloud profile.

Reg 3.) 
Please see https://github.com/gardener/autoscaler/issues/35 for more detailed discussions and conclusions. 

cc @prashanth26 @AxiomSamarth

**Comment by prashanth26** [comment]
Thanks, @hardikdr for discussing the issue. However, I doubt updating these instance resources directly would help. As other stakeholders could run into issues trying to provision a normal machine of this kind. Will need some time to discuss with the team how this could be solved better.
